import type { TestDef, PanelDef } from "./types";

// Prices in paise. Reference ranges reflect common Indian adult lab values;
// the lab can edit prices and ranges in-app. Sex "A" = applies to all.

export const COMMON_TESTS: TestDef[] = [
  {
    code: "CBC",
    name: "Complete Blood Count (CBC)",
    category: "Haematology",
    sampleType: "EDTA Whole Blood",
    method: "Automated Cell Counter",
    defaultPricePaise: 30000,
    tatHours: 4,
    gstExempt: true,
    aliases: ["hemogram", "haemogram", "blood count"],
    analytes: [
      { code: "HB", name: "Haemoglobin", unit: "g/dL", inputType: "numeric", ranges: [
        { sex: "M", low: 13, high: 17, criticalLow: 7, criticalHigh: 20 },
        { sex: "F", low: 12, high: 15, criticalLow: 7, criticalHigh: 20 },
      ]},
      { code: "TLC", name: "Total Leucocyte Count", unit: "cells/cu.mm", inputType: "numeric", ranges: [
        { sex: "A", low: 4000, high: 11000, criticalLow: 2000, criticalHigh: 30000 },
      ]},
      { code: "RBC", name: "RBC Count", unit: "million/cu.mm", inputType: "numeric", ranges: [
        { sex: "M", low: 4.5, high: 5.5 }, { sex: "F", low: 3.8, high: 4.8 },
      ]},
      { code: "PCV", name: "PCV (Haematocrit)", unit: "%", inputType: "numeric", ranges: [
        { sex: "M", low: 40, high: 50 }, { sex: "F", low: 36, high: 46 },
      ]},
      { code: "MCV", name: "MCV", unit: "fL", inputType: "numeric", ranges: [{ sex: "A", low: 80, high: 100 }] },
      { code: "MCH", name: "MCH", unit: "pg", inputType: "numeric", ranges: [{ sex: "A", low: 27, high: 32 }] },
      { code: "MCHC", name: "MCHC", unit: "g/dL", inputType: "numeric", ranges: [{ sex: "A", low: 32, high: 36 }] },
      { code: "PLT", name: "Platelet Count", unit: "lakh/cu.mm", inputType: "numeric", ranges: [
        { sex: "A", low: 1.5, high: 4.1, criticalLow: 0.5, criticalHigh: 10 },
      ]},
      { code: "NEU", name: "Neutrophils", unit: "%", inputType: "numeric", ranges: [{ sex: "A", low: 40, high: 75 }] },
      { code: "LYM", name: "Lymphocytes", unit: "%", inputType: "numeric", ranges: [{ sex: "A", low: 20, high: 45 }] },
      { code: "EOS", name: "Eosinophils", unit: "%", inputType: "numeric", ranges: [{ sex: "A", low: 1, high: 6 }] },
      { code: "MON", name: "Monocytes", unit: "%", inputType: "numeric", ranges: [{ sex: "A", low: 2, high: 10 }] },
      { code: "BAS", name: "Basophils", unit: "%", inputType: "numeric", ranges: [{ sex: "A", low: 0, high: 2 }] },
    ],
  },
  {
    code: "ESR",
    name: "ESR (Erythrocyte Sedimentation Rate)",
    category: "Haematology",
    sampleType: "EDTA Whole Blood",
    method: "Westergren",
    defaultPricePaise: 15000,
    tatHours: 4,
    gstExempt: true,
    analytes: [{ code: "ESR", name: "ESR", unit: "mm/hr", inputType: "numeric", ranges: [
      { sex: "M", low: 0, high: 15 }, { sex: "F", low: 0, high: 20 },
    ]}],
  },
  {
    code: "FBS",
    name: "Blood Sugar Fasting (FBS)",
    category: "Diabetes",
    sampleType: "Fluoride Plasma",
    method: "GOD-POD",
    defaultPricePaise: 8000,
    tatHours: 2,
    gstExempt: true,
    analytes: [{ code: "FBS", name: "Glucose Fasting", unit: "mg/dL", inputType: "numeric", ranges: [
      { sex: "A", low: 70, high: 100, criticalLow: 50, criticalHigh: 400 },
    ]}],
  },
  {
    code: "PPBS",
    name: "Blood Sugar Post Prandial (PPBS)",
    category: "Diabetes",
    sampleType: "Fluoride Plasma",
    method: "GOD-POD",
    defaultPricePaise: 8000,
    tatHours: 2,
    gstExempt: true,
    analytes: [{ code: "PPBS", name: "Glucose PP (2 hr)", unit: "mg/dL", inputType: "numeric", ranges: [
      { sex: "A", low: 70, high: 140, criticalHigh: 400 },
    ]}],
  },
  {
    code: "HBA1C",
    name: "HbA1c (Glycated Haemoglobin)",
    category: "Diabetes",
    sampleType: "EDTA Whole Blood",
    method: "HPLC",
    defaultPricePaise: 45000,
    tatHours: 6,
    gstExempt: true,
    aliases: ["glycosylated"],
    analytes: [
      { code: "HBA1C", name: "HbA1c", unit: "%", inputType: "numeric", ranges: [{ sex: "A", low: 4, high: 5.6, criticalHigh: 10 }] },
      { code: "EAG", name: "Estimated Avg Glucose", unit: "mg/dL", inputType: "numeric", ranges: [{ sex: "A", low: 68, high: 114 }] },
    ],
  },
  {
    code: "LIPID",
    name: "Lipid Profile",
    category: "Biochemistry",
    sampleType: "Serum",
    method: "Enzymatic",
    defaultPricePaise: 60000,
    tatHours: 6,
    gstExempt: true,
    analytes: [
      { code: "TCHOL", name: "Total Cholesterol", unit: "mg/dL", inputType: "numeric", ranges: [{ sex: "A", high: 200 }] },
      { code: "TG", name: "Triglycerides", unit: "mg/dL", inputType: "numeric", ranges: [{ sex: "A", high: 150 }] },
      { code: "HDL", name: "HDL Cholesterol", unit: "mg/dL", inputType: "numeric", ranges: [{ sex: "A", low: 40 }] },
      { code: "LDL", name: "LDL Cholesterol", unit: "mg/dL", inputType: "numeric", ranges: [{ sex: "A", high: 100 }] },
      { code: "VLDL", name: "VLDL Cholesterol", unit: "mg/dL", inputType: "numeric", ranges: [{ sex: "A", low: 7, high: 35 }] },
      { code: "CHR", name: "Total Chol / HDL Ratio", unit: "", inputType: "numeric", ranges: [{ sex: "A", high: 5 }] },
    ],
  },
  {
    code: "LFT",
    name: "Liver Function Test (LFT)",
    category: "Biochemistry",
    sampleType: "Serum",
    defaultPricePaise: 55000,
    tatHours: 6,
    gstExempt: true,
    analytes: [
      { code: "TBIL", name: "Bilirubin Total", unit: "mg/dL", inputType: "numeric", ranges: [{ sex: "A", low: 0.2, high: 1.2, criticalHigh: 15 }] },
      { code: "DBIL", name: "Bilirubin Direct", unit: "mg/dL", inputType: "numeric", ranges: [{ sex: "A", low: 0, high: 0.3 }] },
      { code: "IBIL", name: "Bilirubin Indirect", unit: "mg/dL", inputType: "numeric", ranges: [{ sex: "A", low: 0.1, high: 0.9 }] },
      { code: "SGOT", name: "SGOT (AST)", unit: "U/L", inputType: "numeric", ranges: [{ sex: "A", low: 5, high: 40 }] },
      { code: "SGPT", name: "SGPT (ALT)", unit: "U/L", inputType: "numeric", ranges: [{ sex: "A", low: 5, high: 41 }] },
      { code: "ALP", name: "Alkaline Phosphatase", unit: "U/L", inputType: "numeric", ranges: [{ sex: "A", low: 40, high: 129 }] },
      { code: "TP", name: "Total Protein", unit: "g/dL", inputType: "numeric", ranges: [{ sex: "A", low: 6.4, high: 8.3 }] },
      { code: "ALB", name: "Albumin", unit: "g/dL", inputType: "numeric", ranges: [{ sex: "A", low: 3.5, high: 5.2 }] },
      { code: "GLOB", name: "Globulin", unit: "g/dL", inputType: "numeric", ranges: [{ sex: "A", low: 2, high: 3.5 }] },
    ],
  },
  {
    code: "KFT",
    name: "Kidney Function Test (KFT/RFT)",
    category: "Biochemistry",
    sampleType: "Serum",
    defaultPricePaise: 55000,
    tatHours: 6,
    gstExempt: true,
    aliases: ["rft", "renal"],
    analytes: [
      { code: "UREA", name: "Blood Urea", unit: "mg/dL", inputType: "numeric", ranges: [{ sex: "A", low: 15, high: 40 }] },
      { code: "CREA", name: "Serum Creatinine", unit: "mg/dL", inputType: "numeric", ranges: [
        { sex: "M", low: 0.7, high: 1.3, criticalHigh: 10 }, { sex: "F", low: 0.6, high: 1.1, criticalHigh: 10 },
      ]},
      { code: "UA", name: "Uric Acid", unit: "mg/dL", inputType: "numeric", ranges: [
        { sex: "M", low: 3.5, high: 7.2 }, { sex: "F", low: 2.6, high: 6 },
      ]},
      { code: "NA", name: "Sodium", unit: "mmol/L", inputType: "numeric", ranges: [{ sex: "A", low: 136, high: 145, criticalLow: 120, criticalHigh: 160 }] },
      { code: "K", name: "Potassium", unit: "mmol/L", inputType: "numeric", ranges: [{ sex: "A", low: 3.5, high: 5.1, criticalLow: 2.5, criticalHigh: 6.5 }] },
      { code: "CL", name: "Chloride", unit: "mmol/L", inputType: "numeric", ranges: [{ sex: "A", low: 98, high: 107 }] },
    ],
  },
  {
    code: "THYROID",
    name: "Thyroid Profile (T3 T4 TSH)",
    category: "Hormones",
    sampleType: "Serum",
    method: "CLIA",
    defaultPricePaise: 50000,
    tatHours: 24,
    gstExempt: true,
    analytes: [
      { code: "T3", name: "Total T3", unit: "ng/mL", inputType: "numeric", ranges: [{ sex: "A", low: 0.8, high: 2 }] },
      { code: "T4", name: "Total T4", unit: "µg/dL", inputType: "numeric", ranges: [{ sex: "A", low: 5.1, high: 14.1 }] },
      { code: "TSH", name: "TSH", unit: "µIU/mL", inputType: "numeric", ranges: [{ sex: "A", low: 0.27, high: 4.2, criticalHigh: 100 }] },
    ],
  },
  {
    code: "VITD",
    name: "Vitamin D (25-OH)",
    category: "Hormones",
    sampleType: "Serum",
    method: "CLIA",
    defaultPricePaise: 120000,
    tatHours: 24,
    gstExempt: true,
    analytes: [{ code: "VITD", name: "25-OH Vitamin D", unit: "ng/mL", inputType: "numeric", ranges: [{ sex: "A", low: 30, high: 100 }] }],
  },
  {
    code: "VITB12",
    name: "Vitamin B12",
    category: "Hormones",
    sampleType: "Serum",
    method: "CLIA",
    defaultPricePaise: 90000,
    tatHours: 24,
    gstExempt: true,
    analytes: [{ code: "B12", name: "Vitamin B12", unit: "pg/mL", inputType: "numeric", ranges: [{ sex: "A", low: 211, high: 911 }] }],
  },
  {
    code: "CRP",
    name: "C-Reactive Protein (CRP)",
    category: "Immunology",
    sampleType: "Serum",
    method: "Turbidimetry",
    defaultPricePaise: 40000,
    tatHours: 6,
    gstExempt: true,
    analytes: [{ code: "CRP", name: "CRP", unit: "mg/L", inputType: "numeric", ranges: [{ sex: "A", high: 6 }] }],
  },
  {
    code: "WIDAL",
    name: "Widal Test (Slide)",
    category: "Serology",
    sampleType: "Serum",
    method: "Slide Agglutination",
    defaultPricePaise: 25000,
    tatHours: 6,
    gstExempt: true,
    analytes: [
      { code: "TO", name: "S. Typhi O", inputType: "select", options: ["Non-reactive", "1:40", "1:80", "1:160", "1:320"], defaultText: "Non-reactive" },
      { code: "TH", name: "S. Typhi H", inputType: "select", options: ["Non-reactive", "1:40", "1:80", "1:160", "1:320"], defaultText: "Non-reactive" },
      { code: "AH", name: "S. Paratyphi AH", inputType: "select", options: ["Non-reactive", "1:40", "1:80", "1:160", "1:320"], defaultText: "Non-reactive" },
      { code: "BH", name: "S. Paratyphi BH", inputType: "select", options: ["Non-reactive", "1:40", "1:80", "1:160", "1:320"], defaultText: "Non-reactive" },
    ],
  },
  {
    code: "DENGUE",
    name: "Dengue NS1 Antigen",
    category: "Serology",
    sampleType: "Serum",
    method: "Rapid / ELISA",
    defaultPricePaise: 60000,
    tatHours: 6,
    gstExempt: true,
    analytes: [{ code: "NS1", name: "Dengue NS1 Antigen", inputType: "select", options: ["Negative", "Positive"], defaultText: "Negative" }],
  },
  {
    code: "BLOODGRP",
    name: "Blood Group & Rh Typing",
    category: "Immunohaematology",
    sampleType: "EDTA Whole Blood",
    defaultPricePaise: 15000,
    tatHours: 2,
    gstExempt: true,
    analytes: [
      { code: "ABO", name: "ABO Group", inputType: "select", options: ["A", "B", "AB", "O"] },
      { code: "RH", name: "Rh (D) Type", inputType: "select", options: ["Positive", "Negative"] },
    ],
  },
  {
    code: "URINE",
    name: "Urine Routine & Microscopy",
    category: "Clinical Pathology",
    sampleType: "Urine",
    defaultPricePaise: 15000,
    tatHours: 4,
    gstExempt: true,
    analytes: [
      { code: "COLOR", name: "Colour", inputType: "text", defaultText: "Pale Yellow" },
      { code: "APP", name: "Appearance", inputType: "select", options: ["Clear", "Slightly Turbid", "Turbid"], defaultText: "Clear" },
      { code: "PH", name: "pH", unit: "", inputType: "numeric", ranges: [{ sex: "A", low: 5, high: 8 }] },
      { code: "SPG", name: "Specific Gravity", unit: "", inputType: "numeric", ranges: [{ sex: "A", low: 1.005, high: 1.03 }] },
      { code: "PROT", name: "Protein (Albumin)", inputType: "select", options: ["Nil", "Trace", "+", "++", "+++"], defaultText: "Nil" },
      { code: "SUG", name: "Sugar", inputType: "select", options: ["Nil", "Trace", "+", "++", "+++"], defaultText: "Nil" },
      { code: "PUS", name: "Pus Cells", unit: "/hpf", inputType: "text", defaultText: "1-2" },
      { code: "RBCU", name: "RBCs", unit: "/hpf", inputType: "text", defaultText: "Nil" },
      { code: "EPI", name: "Epithelial Cells", unit: "/hpf", inputType: "text", defaultText: "Occasional" },
    ],
  },
];

export const COMMON_PANELS: PanelDef[] = [
  {
    code: "PKG-HEALTH",
    name: "Complete Health Check-up",
    category: "Package",
    testCodes: ["CBC", "FBS", "LIPID", "LFT", "KFT", "THYROID", "URINE"],
    defaultPricePaise: 149900,
  },
  {
    code: "PKG-FEVER",
    name: "Fever Panel",
    category: "Package",
    testCodes: ["CBC", "WIDAL", "DENGUE"],
    defaultPricePaise: 99900,
  },
  {
    code: "PKG-DIABETIC",
    name: "Diabetic Check-up",
    category: "Package",
    testCodes: ["FBS", "PPBS", "HBA1C", "KFT", "URINE"],
    defaultPricePaise: 99900,
  },
];
